# ClickHouse Installation CR (requires ClickHouse Operator)
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{ .Release.Name }}-clickhouse
  labels:
    app.kubernetes.io/name: seebom
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  configuration:
    clusters:
      - name: {{ .Values.clickhouse.cluster.name }}
        templates:
          podTemplate: pod-template
          dataVolumeClaimTemplate: data-volume-template
          logVolumeClaimTemplate: log-volume-template
        layout:
          shardsCount: {{ .Values.clickhouse.cluster.shardsCount }}
          replicasCount: {{ .Values.clickhouse.cluster.replicasCount }}
    users:
      {{- if .Values.clickhouse.userPasswordSecret.enabled }}
      {{ .Values.clickhouse.user }}/password:
        valueFrom:
          secretKeyRef:
            name: {{ .Values.clickhouse.userPasswordSecret.secretName }}
            key: {{ .Values.clickhouse.userPasswordSecret.key }}
      {{- else }}
      {{ .Values.clickhouse.user }}/password: {{ .Values.clickhouse.password | quote }}
      {{- end }}
      {{ .Values.clickhouse.user }}/networks/ip: "::/0"
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: {{ .Values.clickhouse.installation.podTemplate.containerImage }}
              resources: {{ toYaml .Values.clickhouse.installation.podTemplate.resources | nindent 16 }}
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.installation.volumeClaimTemplate.dataStorage }}
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.installation.volumeClaimTemplate.logStorage }}
