{{- if not .Values.gitSync.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sbomSource.pvcName }}
  labels:
    app.kubernetes.io/name: seebom
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sbomSource.storageSize | default "1Gi" }}
{{- end }}

