{{- $password := "" }}
{{- if .Values.clickhouse.userPasswordSecret.enabled }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.clickhouse.userPasswordSecret.secretName }}
  {{- $password = index $existingSecret.data .Values.clickhouse.userPasswordSecret.key }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: seebom
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.clickhouse.userPasswordSecret.enabled }}
  CLICKHOUSE_PASSWORD: {{ $password | quote }}
  {{- else }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.github.token }}
  GITHUB_TOKEN: {{ .Values.github.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3.accessKey }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3.secretKey }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc | quote }}
  {{- end }}
