{{- $password := "" }}
{{- if .Values.clickhouse.userPasswordSecret.enabled }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace .Values.clickhouse.userPasswordSecret.secretName }}
  {{- $password = index $existingSecret.data .Values.clickhouse.userPasswordSecret.key }}
{{- end }}
{{- $s3AccessKey := "" }}
{{- $s3SecretKey := "" }}
{{- if .Values.s3.credentialsSecret.enabled }}
  {{- $existingS3Secret := lookup "v1" "Secret" .Release.Namespace .Values.s3.credentialsSecret.secretName }}
  {{- if $existingS3Secret }}
  {{- $s3AccessKey = index $existingS3Secret.data .Values.s3.credentialsSecret.accessKeyKey }}
  {{- $s3SecretKey = index $existingS3Secret.data .Values.s3.credentialsSecret.secretKeyKey }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: seebom
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.clickhouse.userPasswordSecret.enabled }}
  CLICKHOUSE_PASSWORD: {{ $password | quote }}
  {{- else }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.github.token }}
  GITHUB_TOKEN: {{ .Values.github.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3.credentialsSecret.enabled }}
  {{- if $s3AccessKey }}
  S3_ACCESS_KEY: {{ $s3AccessKey | quote }}
  {{- end }}
  {{- if $s3SecretKey }}
  S3_SECRET_KEY: {{ $s3SecretKey | quote }}
  {{- end }}
  {{- else }}
  {{- if .Values.s3.accessKey }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3.secretKey }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc | quote }}
  {{- end }}
  {{- end }}
